#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <subnet_calculator_icons.h>

int32_t subnet_calculator_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm subnet_calculator!");

    return 0;
}
