#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

#define TAG "subnet-calculator"
/* generated by fbt from .png files in images folder */
#include <subnet_calculator_icons.h>

typedef enum { // Tracks the scenes
    SubnetCalculatorScene_MainMenu,
    SubnetCalculatorScene_FirstPopup,
    SubnetCalculatorScene_SecondPopup,
    SubnetCalculatorScene_count
} SubnetCalculatorScene; // Names the typedef

typedef enum { // Tracks the views
    SubnetCalculatorView_Menu,
    SubnetCalculatorView_Popup
} SubnetCalculatorView;

// Subnet Calculator context struct
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} SubnetCalculator;

// All custom events
typedef enum { SubnetCalculatorEvent_ShowPopupOne, SubnetCalculatorEvent_ShowPopupTwo } SubnetCalculatorEvent;

// Main menu scene

// Indices for menu items
typedef enum { SubnetCalculatorMenuSelection_One, SubnetCalculatorMenuSelection_Two } SubnetCalculatorMenuSelection;

// Main menu callback -sends a custom event to the scene manager based on the menu selection
void subnet_calculator_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "subnet_calculator_menu_callback_main_menu");
    SubnetCalculator* app = context;
    switch(index) {
        case SubnetCalculatorMenuSelection_One:
            scene_manager_handle_custom_event(app->scene_manager, SubnetCalculatorEvent_ShowPopupOne);
            break;
        case SubnetCalculatorMenuSelection_Two:
            scene_manager_handle_custom_event(app->scene_manager, SubnetCalculatorEvent_ShowPopupTwo);
            break;
    }
}

// Resets the menu, gives it context, callbacks, and selection enums
void subnet_calculator_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_enter_main_menu");
    SubnetCalculator* app = context;
    menu_reset(app->menu);

    // NB. icons are specified as NULL below, because:
    // * icons are _always_ animated by the menu
    // * the icons provided (&I_one, &I_two) are generated by the build process
    // * these icons do not have a framerate (resulting in a division by zero)
    menu_add_item(
            app->menu,
            "First popup",
            NULL,
            SubnetCalculatorMenuSelection_One,
            subnet_calculator_menu_callback_main_menu,
            app);
    menu_add_item(
            app->menu,
            "Second popup",
            NULL,
            SubnetCalculatorMenuSelection_Two,
            subnet_calculator_menu_callback_main_menu,
            app);
    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalculatorView_Menu);
}

// Main menu event handler - switches scene based on the event
bool subnet_calculator_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_event_main_menu");
    SubnetCalculator* app = context;
    bool consumed = false;
    switch(event.event) {
        case SceneManagerEventTypeCustom:
            switch(event.event) {
                case SubnetCalculatorEvent_ShowPopupOne:
                    scene_manager_next_scene(app->scene_manager, SubnetCalculatorScene_FirstPopup);
                    consumed = true;
                    break;
                case SubnetCalculatorEvent_ShowPopupTwo:
                    scene_manager_next_scene(app->scene_manager, SubnetCalculatorScene_SecondPopup);
                    consumed = true;
                    break;
            }
            break;
        default: // e.g. SceneManagerEventTypeBack, SceneManagerEventTypeTick
            consumed = false;
            break;
    }
    return consumed;
}

void subnet_calculator_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_exit_main_menu");
    SubnetCalculator* app = context;
    menu_reset(app->menu);
}

// Popup 1 scene
void subnet_calculator_scene_on_enter_popup_one(void* context) {
    FURI_LOG_T(TAG, "subnet_Calculator_scene_on_enter_popup_one");
    SubnetCalculator* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup One", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
    popup_set_text(app->popup, "One! One popup. Ah ah ah...", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalculatorView_Popup);
}

bool subnet_calculator_scene_on_event_popup_one(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_event_popup_one");
    UNUSED(context);
    UNUSED(event);
    return false; // Don't handle any events
}

void subnet_calculator_scene_on_exit_popup_one(void* context) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_exit_popup_one");
    SubnetCalculator* app = context;
    popup_reset(app->popup);
}

// Popup 2 scene
void subnet_calculator_scene_on_enter_popup_two(void* context) {
    FURI_LOG_T(TAG, "subnet_Calculator_scene_on_enter_popup_two");
    SubnetCalculator* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup Two", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
    popup_set_text(app->popup, "Two! Two popups. Ah ah ah...", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalculatorView_Popup);
}

bool subnet_calculator_scene_on_event_popup_two(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_event_popup_two");
    UNUSED(context);
    UNUSED(event);
    return false; // Don't handle any events
}

void subnet_calculator_scene_on_exit_popup_two(void* context) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_on_exit_popup_two");
    SubnetCalculator* app = context;
    popup_reset(app->popup);
}

// Collection of all scene on_enter handlers
void (*const subnet_calculator_scene_on_enter_handlers[])(void*) = {
        subnet_calculator_scene_on_enter_main_menu,
        subnet_calculator_scene_on_enter_popup_one,
        subnet_calculator_scene_on_enter_popup_two};

// Collection of all scene on event handlers
bool (*const subnet_calculator_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
        subnet_calculator_scene_on_event_main_menu,
        subnet_calculator_scene_on_event_popup_one,
        subnet_calculator_scene_on_event_popup_two};

// Collection of all scene on exit handlers
void (*const subnet_calculator_scene_on_exit_handlers[])(void*) = {
        subnet_calculator_scene_on_exit_main_menu,
        subnet_calculator_scene_on_exit_popup_one,
        subnet_calculator_scene_on_exit_popup_two};

// Collection of all on_enter, on_event, on_exit handlers
const SceneManagerHandlers subnet_calculator_scene_event_handlers = {
        .on_enter_handlers = subnet_calculator_scene_on_enter_handlers,
        .on_event_handlers = subnet_calculator_scene_on_event_handlers,
        .on_exit_handlers = subnet_calculator_scene_on_exit_handlers,
        .scene_num = SubnetCalculatorScene_count};

// Custom event handler - passes the event to the scene manager
bool subnet_calculator_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_manager_custom_event_callback");
    furi_assert(context);
    SubnetCalculator* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

// Navigation event handler - passes the event to the scene manager
bool subnet_calculator_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "subnet_calculator_scene_manager_navigation_event_callback");
    furi_assert(context);
    SubnetCalculator* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

// Initialise the scene manager with all handler
void subnet_calculator_scene_manager_init(SubnetCalculator* app) {
    FURI_LOG_T(TAG, "subnet_calculator_manager_init");
    app->scene_manager = scene_manager_alloc(&subnet_calculator_scene_event_handlers, app); // Allocates memory for a SceneManager
}

// Initialise the views, and initialise the view dispatcher with all views
void subnet_calculator_view_dispatcher_init(SubnetCalculator* app) {
    FURI_LOG_T(TAG, "subnet_calculator_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    // Allocate each view
    FURI_LOG_D(TAG, "subnet_calculator_view_dispatcher_init allocating views");
    app->menu = menu_alloc();
    app->popup = popup_alloc();

    // Assign callback that pass events from views to the scene manager
    FURI_LOG_D(TAG, "subnet_calculator_view_dispatcher_init setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, subnet_calculator_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(app->view_dispatcher, subnet_calculator_scene_manager_navigation_event_callback);

    // Add views to the dispatcher, indexed by their enum value
    FURI_LOG_D(TAG, "subnet_calculator_view_dispatcher_init adding view menu");
    view_dispatcher_add_view(app->view_dispatcher, SubnetCalculatorView_Menu, menu_get_view(app->menu));

    FURI_LOG_D(TAG, "subnet_calculator_view_dispatcher_init adding view popup");
    view_dispatcher_add_view(app-> view_dispatcher, SubnetCalculatorView_Popup, popup_get_view(app->popup));
}

// Initialise app data, scene manager, and view dispatcher
SubnetCalculator* subnet_calculator_init() {
    FURI_LOG_T(TAG,"subnet_calculator_init");
    SubnetCalculator* app = malloc(sizeof(SubnetCalculator));
    subnet_calculator_scene_manager_init(app);
    subnet_calculator_view_dispatcher_init(app);
    return app;
}

// Free all app data, scene manager, and view dispatcher
void subnet_calculator_free(SubnetCalculator* app) {
    FURI_LOG_T(TAG, "subnet_calculator_free");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, SubnetCalculatorView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, SubnetCalculatorView_Popup);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    free(app);
}

// Go to trace log level in the dev environment
void subnet_calculator_set_log_leve() {
#ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelInfo);
#endif
}

// Entrypoint
int32_t subnet_calculator_app(void* p) {
    UNUSED(p);
    subnet_calculator_set_log_leve();

    // Create the app context structs, scene manager, and view dispatcher
    FURI_LOG_I(TAG, "Subnet Calculator starting...");
    SubnetCalculator* app = subnet_calculator_init();

    // Set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, SubnetCalculatorScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // Free all memory
    FURI_LOG_I(TAG, "Subnet Calculator finishing...");
    furi_record_close(RECORD_GUI);
    subnet_calculator_free(app);
    return 0;
}